package pruebabd;

import javax.swing.table.DefaultTableModel;

public class Interfaz extends javax.swing.JFrame {

    public Interfaz() {
        initComponents();
        model = (DefaultTableModel) tabla.getModel();
    }
    metodos m = new metodos();
    DefaultTableModel model;
    
    public DefaultTableModel getModel(){
        return model;
    }
    
    public void setModel(DefaultTableModel model){
        this.model=model;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bConectarse = new javax.swing.JButton();
        bDesconectarse = new javax.swing.JButton();
        bCreateTable = new javax.swing.JButton();
        bInsertValues = new javax.swing.JButton();
        bSelect = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tOutput = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("BASE DE DATOS RELACIONAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 17, -1, -1));

        bConectarse.setText("Conectarse");
        bConectarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConectarseActionPerformed(evt);
            }
        });
        getContentPane().add(bConectarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 12, -1, -1));

        bDesconectarse.setText("Desconectarse");
        bDesconectarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDesconectarseActionPerformed(evt);
            }
        });
        getContentPane().add(bDesconectarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 12, -1, -1));

        bCreateTable.setText("Crear Tabla");
        bCreateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreateTableActionPerformed(evt);
            }
        });
        getContentPane().add(bCreateTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 55, -1, -1));

        bInsertValues.setText("Insertar Valores");
        bInsertValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsertValuesActionPerformed(evt);
            }
        });
        getContentPane().add(bInsertValues, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 55, -1, -1));

        bSelect.setText("Select");
        bSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelectActionPerformed(evt);
            }
        });
        getContentPane().add(bSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 55, -1, -1));

        bUpdate.setText("Update");
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(bUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 55, -1, -1));

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(bDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 55, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Edade", "Rua"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, 470, 113));

        tOutput.setColumns(20);
        tOutput.setRows(5);
        jScrollPane1.setViewportView(tOutput);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 170, 150));

        jLabel2.setText("OUTPUT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConectarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConectarseActionPerformed
        m.connect();
    }//GEN-LAST:event_bConectarseActionPerformed

    private void bDesconectarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDesconectarseActionPerformed
        m.close();
    }//GEN-LAST:event_bDesconectarseActionPerformed

    private void bCreateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateTableActionPerformed
        m.crearTabla();
    }//GEN-LAST:event_bCreateTableActionPerformed

    private void bInsertValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInsertValuesActionPerformed
        m.insertarValores();
    }//GEN-LAST:event_bInsertValuesActionPerformed

    private void bSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelectActionPerformed
        m.select(model);
    }//GEN-LAST:event_bSelectActionPerformed

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        m.Updatear();
    }//GEN-LAST:event_bUpdateActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        m.Delete();
    }//GEN-LAST:event_bDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bConectarse;
    private javax.swing.JButton bCreateTable;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bDesconectarse;
    private javax.swing.JButton bInsertValues;
    private javax.swing.JButton bSelect;
    private javax.swing.JButton bUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tOutput;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
